#!/bin/sh 

# support sourcing this script without executing it
if [[ $_ == $0 ]]; then
	execute=1
fi

# Create a data URL from a file
function dataurl() {
	local mimeType=$(file -b --mime-type "$1");
	if [[ $mimeType == text/* ]]; then
		mimeType="${mimeType};charset=utf-8";
	fi
	echo "data:${mimeType};base64,$(openssl base64 -in "$1" | tr -d '\n')";
}

if [ "$execute" = 1 ]; then
    dataurl "$@"
fi
