#!/bin/sh
exec env GIT_DIR="$HOME/.dotfiles.git" GIT_WORK_TREE="$HOME" git $@


# Portable dotfiles system based on this technique:
# https://yokekeong.com/note-on-tracking-dotfiles-across-multiple-instances-easily-with-git/

# To install:
git clone --bare git@github.com:USERNAME/dotfiles.git ~/.dotfiles.git
GIT_DIR=~/.dotfiles.git GIT_WORK_TREE=~ git checkout

# and make sure ~/bin is in your PATH, then you can run:
dit status
